version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  postgresql:
    image: postgres:latest
    container_name: postgresql
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: cms_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgresql_data:/var/lib/postgresql/data

volumes:
  mongodb_data:
  postgresql_data:
